name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: touch laravel_test.txt
    - name: Execute php artisan test
      run: php artisan test
  
